# bump to force rebuild
{% set name = "safeint" %}
{% set version = "3.0.26" %}
{% set sha256 = "62fef99873ad975ddd8356923b3d51ed316209c1a05ac85814219373a13ae4d5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcleblanc/SafeInt/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/include/SafeInt.hpp  # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\SafeInt.hpp exit 1  # [win]

about:
  home: https://github.com/dcleblanc/SafeInt 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SafeInt is a class library for C++ that manages integer overflows.
  description: SafeInt is a class library for C++ that manages integer overflows.
  dev_url: https://github.com/dcleblanc/SafeInt
  doc_url: https://github.com/dcleblanc/SafeInt/blob/master/README.md

extra:
  recipe-maintainers:
    - xhochy
